/**
 * Los iconos que usa la app, registrados uno por uno.
 *
 * Font Awesome entero pesa megas. Importando solo los que se pintan, el bundle
 * carga lo que se ve y nada más.
 */
import { library } from '@fortawesome/fontawesome-svg-core'
import {
  faDumbbell,
  faPlay,
  faCirclePlay,
  faCreditCard,
  faUser,
  faRightFromBracket,
  faBagShopping,
  faFilm,
  faComments,
  faLock,
  faCheck,
  faClock,
  faArrowLeft,
  faArrowRight,
  faPaperPlane,
  faEye,
  faEyeSlash,
  faTrash,
  faReply,
  faCircleQuestion,
  faUtensils,
  faHeartPulse,
  faBookOpen,
  faUsers,
  faChartLine,
  faCalendarCheck,
  faTriangleExclamation,
  faSpinner,
  faXmark,
  faBars,
} from '@fortawesome/free-solid-svg-icons'
import { faWhatsapp } from '@fortawesome/free-brands-svg-icons'

library.add(
  faDumbbell,
  faPlay,
  faCirclePlay,
  faCreditCard,
  faUser,
  faRightFromBracket,
  faBagShopping,
  faFilm,
  faComments,
  faLock,
  faCheck,
  faClock,
  faArrowLeft,
  faArrowRight,
  faPaperPlane,
  faEye,
  faEyeSlash,
  faTrash,
  faReply,
  faCircleQuestion,
  faUtensils,
  faHeartPulse,
  faBookOpen,
  faUsers,
  faChartLine,
  faCalendarCheck,
  faTriangleExclamation,
  faSpinner,
  faXmark,
  faBars,
  faWhatsapp,
)
